UserError.configure do
  #rescue_from 'My::Exception', with: :forbidden
end